## Stage 1 : create the docker applicaiton image
## Specifying arm64 architecture for Mac M1
FROM quay.io/quarkus/ubi-quarkus-mandrel:22.1-java11-arm64 AS build
USER root
# COPY --chown=1001:1001 certs  /tmp/certs
# COPY --chown=1001:1001 settings.xml  /code/
# COPY --chown=1001:1001 .quarkus  $HOME/.quarkus

COPY --chown=1001:1001 mvnw /code/mvnw
COPY --chown=1001:1001 .mvn /code/.mvn
COPY --chown=1001:1001 pom.xml /code/

# RUN for f in /tmp/certs/* ; \
#         do keytool -import -trustcacerts -keystore cacerts  -storepass changeit -alias `echo $(basename $f)` -noprompt -file $f ; \
#     done;

USER 1001
WORKDIR /code/
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /code/src
RUN ./mvnw clean package -Pnative -Drelease.version=1.0 -Dmaven.test.skip=true  


## Stage 2 : create the docker final image
## quarkus-micro-image is not available in arm64 architecture so we have to use something else that is
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --from=build --chown=1001:root /code/target/*-runner /work/application

## Expose 9080 as well as 9443
EXPOSE 9080 9443
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
